# Generated by Django 5.2.11 on 2026-04-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_object_labels_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrental',
            name='reminder_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
