# Generated by Django 5.2.13 on 2026-04-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_objectrental_reminder_viewed_at'),
        ('objects', '0008_objectrental_user_dismissed_at'),
    ]

    operations = [
    ]
