# Generated by Django 5.2.12 on 2026-03-15 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0002_membership_bedroom'),
        ('residences', '0004_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name_snapshot', models.CharField(max_length=200)),
                ('room_snapshot', models.CharField(max_length=50)),
                ('building_snapshot', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('DELIVERED', 'Entregado')], db_index=True, default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('resident_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resident_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='residences.residence')),
                ('resident', models.ForeignKey(limit_choices_to={'role__name__iexact': 'Student'}, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='membership.membership')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['residence', 'status'], name='packages_pa_residen_5d1ab2_idx'), models.Index(fields=['resident', 'status'], name='packages_pa_residen_43459b_idx'), models.Index(fields=['residence', 'resident_viewed_at'], name='packages_pa_residen_b7a47c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'DELIVERED'), ('delivered_at__isnull', False)), models.Q(models.Q(('status', 'DELIVERED'), _negated=True), ('delivered_at__isnull', True)), _connector='OR'), name='package_delivered_at_matches_status')],
            },
        ),
    ]
