# Generated by Django 5.2.12 on 2026-03-23 22:17

import apps.packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_code',
            field=models.CharField(default=apps.packages.models.generate_delivery_code, max_length=5),
        ),
    ]
