# Generated by Django 5.2.12 on 2026-05-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="notes",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
