# Generated by Django 5.2.12 on 2026-04-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chatgroupmember_interaction_disabled_at'),
        ('events', '0002_event_internal_external_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='chats.chatgroup'),
        ),
    ]
