# Generated by Django 5.2.12 on 2026-03-17 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_spaces",
                        to="residences.residence",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpaceReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("cancelled", "Cancelada")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_reservations",
                        to="residences.residence",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="spaces.commonspace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="commonspace",
            constraint=models.UniqueConstraint(
                fields=("residence", "name"), name="uniq_common_space_name_residence"
            ),
        ),
        migrations.AddConstraint(
            model_name="commonspace",
            constraint=models.CheckConstraint(
                condition=models.Q(("close_time__gt", models.F("open_time"))),
                name="common_space_close_after_open",
            ),
        ),
        migrations.AddIndex(
            model_name="spacereservation",
            index=models.Index(
                fields=["residence", "space", "status", "start_time"],
                name="spaces_spac_residen_050eae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spacereservation",
            index=models.Index(
                fields=["residence", "user", "status", "start_time"],
                name="spaces_spac_residen_2ba088_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="spacereservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="space_reservation_end_after_start",
            ),
        ),
    ]
