# Generated by Django 5.2.11 on 2026-03-02 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0002_residencedomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_spaces', to='residences.residence')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [
                    models.UniqueConstraint(fields=('residence', 'name'), name='uniq_common_space_name_residence'),
                    models.CheckConstraint(condition=models.Q(('close_time__gt', models.F('open_time'))), name='common_space_close_after_open'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SpaceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reservations', to='residences.residence')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='spaces.commonspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [
                    models.Index(fields=['residence', 'space', 'status', 'start_time'], name='spaces_spac_residen_d57dd2_idx'),
                    models.Index(fields=['residence', 'user', 'status', 'start_time'], name='spaces_spac_residen_eb8fdb_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='space_reservation_end_after_start'),
                ],
            },
        ),
    ]
