# Generated by Django 5.2.12 on 2026-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonspace",
            name="reservation_interval_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
