# Generated by Django 5.2.11 on 2026-03-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spacereservation',
            new_name='spaces_spac_residen_050eae_idx',
            old_name='spaces_spac_residen_d57dd2_idx',
        ),
        migrations.RenameIndex(
            model_name='spacereservation',
            new_name='spaces_spac_residen_2ba088_idx',
            old_name='spaces_spac_residen_eb8fdb_idx',
        ),
    ]
