# Generated by Django 5.2.12 on 2026-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_commonspace_reservation_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspace',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
