# Generated by Django 5.2.12 on 2026-03-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0003_bedroom_unique_room_per_residence'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bedroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='bedrooms.bedroom', verbose_name='Habitación Asignada'),
        ),
    ]
