# Generated by Django 5.2.12 on 2026-03-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Día de la semana')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Día del menú',
                'verbose_name_plural': 'Días del menú',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('dinner', 'Cena'), ('snack', 'Merienda')], default='lunch', max_length=10, verbose_name='Tipo de comida')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Sin gluten')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariano')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegano')),
                ('image_url', models.URLField(blank=True, max_length=5000, null=True, verbose_name='URL de la imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('menu_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='menu.menuday', verbose_name='Día del menú')),
            ],
        ),
        migrations.CreateModel(
            name='MenuWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Inicio de la semana')),
                ('week_end', models.DateField(verbose_name='Fin de la semana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_weeks_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_weeks', to='tenants.client', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Menú semanal',
                'verbose_name_plural': 'Menús semanales',
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='menuday',
            name='menu_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='menu.menuweek', verbose_name='Semana'),
        ),
        migrations.CreateModel(
            name='SpecialMenuRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha solicitada')),
                ('description', models.TextField(verbose_name='Motivo/Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_menu_requests', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Petición especial',
                'verbose_name_plural': 'Peticiones especiales',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='menuweek',
            index=models.Index(fields=['residence', 'week_start'], name='menu_menuwe_residen_d0abd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuweek',
            unique_together={('residence', 'week_start')},
        ),
        migrations.AlterUniqueTogether(
            name='menuday',
            unique_together={('menu_week', 'date')},
        ),
    ]
