# Generated by Django 5.2.13 on 2026-04-09 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialmenurequest',
            name='resident',
        ),
        migrations.AddField(
            model_name='specialmenurequest',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='special_menu_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
