# Generated by Django 5.2.13 on 2026-04-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_specialmenurequest_resident_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmenurequest',
            name='residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='special_menu_requests', to='tenants.client', verbose_name='Residencia'),
            preserve_default=False,
        ),
    ]
