# Generated by Django 5.2.13 on 2026-04-15 11:40

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_specialmenurequest_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, default='', validators=[apps.menu.models.validate_not_digit], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.menu.models.validate_not_digit], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='specialmenurequest',
            name='description',
            field=models.TextField(validators=[apps.menu.models.validate_not_digit], verbose_name='Motivo/Descripción'),
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='meals', to='menu.allergen', verbose_name='Alérgenos'),
        ),
    ]
