# Generated by Django 5.2.13 on 2026-04-15 11:58

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_allergen_alter_meal_description_alter_meal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='allergens',
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.TextField(blank=True, default='', help_text='Ejemplo: Gluten, Lactosa, Frutos de cáscara', max_length=100, validators=[apps.menu.models.validate_not_digit], verbose_name='Alérgenos'),
        ),
    ]
