# Generated by Django 5.2.12 on 2026-04-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Compatibility score in range [0, 1].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to='residences.residence')),
                ('source_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities_as_source', to='membership.membership')),
                ('target_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities_as_target', to='membership.membership')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['residence', 'source_membership', '-score'], name='idx_comp_res_src_score'), models.Index(fields=['residence', 'target_membership'], name='idx_comp_res_tgt')],
                'constraints': [models.UniqueConstraint(fields=('residence', 'source_membership', 'target_membership'), name='uniq_residence_source_target_compatibility'), models.CheckConstraint(condition=models.Q(('source_membership', models.F('target_membership')), _negated=True), name='compatibility_source_target_distinct')],
            },
        ),
    ]
