# Generated by Django 5.2.13 on 2026-04-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('membership', '0001_initial'),
        ('residences', '0002_delete_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_likes', to='residences.residence')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_likes_given', to='membership.membership')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_likes_received', to='membership.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['residence', 'source'], name='matching_ma_residen_17dc9a_idx'), models.Index(fields=['residence', 'target'], name='matching_ma_residen_88c50b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='match_like_unique_source_target'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='match_like_no_self')],
            },
        ),
    ]
