# Generated by Django 5.2.5 on 2026-03-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("membership", "0002_membership_bedroom"),
        ("residences", "0004_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("id_document", models.CharField(blank=True, max_length=80)),
                ("pass_code", models.CharField(max_length=40)),
                ("access_type", models.CharField(blank=True, max_length=60)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("USED", "Usada"),
                            ("REVOKED", "Revocada"),
                            ("CANCELLED", "Cancelada"),
                            ("REJECTED", "Rechazada"),
                            ("INACTIVE", "Inactiva"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_passes",
                        to="residences.residence",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        limit_choices_to={"role__name__iexact": "Student"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_passes",
                        to="membership.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["valid_until", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["residence", "resident", "status"],
                        name="guests_gues_residen_2d6238_idx",
                    ),
                    models.Index(
                        fields=["residence", "status", "valid_until"],
                        name="guests_gues_residen_67d52f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("residence", "pass_code"),
                        name="uniq_guest_pass_code_per_residence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(valid_until__gt=models.F("valid_from")),
                        name="guest_pass_valid_until_after_valid_from",
                    ),
                ],
            },
        ),
    ]
