# Generated by Django 5.2.13 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpasspolicy',
            name='visit_end_time',
            field=models.TimeField(blank=True, help_text='Hora límite diaria para finalizar visitas (HH:MM).', null=True),
        ),
        migrations.AddField(
            model_name='guestpasspolicy',
            name='visit_start_time',
            field=models.TimeField(blank=True, help_text='Hora diaria de inicio permitida para visitas (HH:MM).', null=True),
        ),
    ]
