# Generated by Django 5.2.12 on 2026-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatgroup_label_groupmessage_and_more'),
        ('membership', '0001_initial'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='privateconversation',
            constraint=models.CheckConstraint(condition=models.Q(('member_one__lt', models.F('member_two'))), name='check_member_order'),
        ),
    ]
