# Generated by Django 5.2.12 on 2026-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_fix_duplicate_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgrouplabel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
