# Generated by Django 5.2.12 on 2026-03-03 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('room', models.CharField(max_length=10, verbose_name='Habitación')),
                ('building', models.CharField(max_length=100, verbose_name='Edificio')),
                ('check_in_date', models.DateField(default=datetime.date(2026, 3, 3), verbose_name='Fecha de Registro')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
