# Generated by Django 5.2.13 on 2026-04-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_ranges(apps, schema_editor):
    StudentProfile = apps.get_model('residences', 'StudentProfile')
    profiles = []
    
    for profile in StudentProfile.objects.all():
        updated = False
        if profile.study_level < 1:
            profile.study_level = 1
            updated = True
        elif profile.study_level > 5:
            profile.study_level = 5
            updated = True
            
        if profile.noise_sensitivity < 1:
            profile.noise_sensitivity = 1
            updated = True
        elif profile.noise_sensitivity > 5:
            profile.noise_sensitivity = 5
            updated = True
            
        if updated:
            profiles.append(profile)
            
    if profiles:
        StudentProfile.objects.bulk_update(profiles, ['study_level', 'noise_sensitivity'])


def _copy_student_profiles(source_model, target_model):
    profiles_to_create = []

    for profile in source_model.objects.all().iterator():
        profiles_to_create.append(
            target_model(
                id=profile.id,
                user_id=profile.user_id,
                residence_id=profile.residence_id,
                nickname=(profile.nickname or "")[:30],
                bio=profile.bio,
                birth_year=profile.birth_year,
                birthplace=profile.birthplace,
                room_number=profile.room_number,
                profile_image=profile.profile_image,
                chronotype=profile.chronotype,
                study_level=profile.study_level,
                noise_sensitivity=profile.noise_sensitivity,
                temperature_preference=profile.temperature_preference,
                order_level=profile.order_level,
                interests=profile.interests,
                custom_interests=profile.custom_interests,
                lifestyle=profile.lifestyle,
                music_genres=profile.music_genres,
                dealbreakers=profile.dealbreakers,
                created_at=profile.created_at,
                updated_at=profile.updated_at,
            )
        )
        
        if len(profiles_to_create) >= 500:
            target_model.objects.bulk_create(profiles_to_create)
            profiles_to_create = []

    if profiles_to_create:
        target_model.objects.bulk_create(profiles_to_create)


def _copy_profiles_between_apps(apps, source_app_label, target_app_label):
    source_student_profile = apps.get_model(source_app_label, 'StudentProfile')
    target_student_profile = apps.get_model(target_app_label, 'StudentProfile')

    _copy_student_profiles(source_student_profile, target_student_profile)


def copy_old_to_new(apps, schema_editor):
    _copy_profiles_between_apps(apps, 'residences', 'residents')


def restore_old_from_new(apps, schema_editor):
    _copy_profiles_between_apps(apps, 'residents', 'residences')


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(max_length=300, blank=True)),
                ('birth_year', models.IntegerField(null=True, blank=True)),
                ('birthplace', models.CharField(max_length=255, blank=True)),
                ('room_number', models.CharField(max_length=20, blank=True)),
                ('profile_image', models.ImageField(upload_to='profiles/', null=True, blank=True)),
                ('chronotype', models.CharField(max_length=20, choices=[('morning', 'Madrugador/a'), ('midday', 'Normal'), ('night', 'Nocturno/a')], blank=True)),
                ('study_level', models.IntegerField(help_text='1-5 scale', default=3)),
                ('noise_sensitivity', models.IntegerField(help_text='1-5 scale', default=3)),
                ('temperature_preference', models.CharField(max_length=20, choices=[('cold', 'Frío'), ('cool', 'Fresco'), ('warm', 'Cálido'), ('hot', 'Muy cálido')], blank=True)),
                ('order_level', models.CharField(max_length=20, choices=[('very_messy', 'Muy desorganizado'), ('somewhat_messy', 'Un poco desordenado'), ('organized', 'Organizado'), ('very_organized', 'Muy organizado')], blank=True)),
                ('interests', models.JSONField(help_text='List of interest strings', default=list, blank=True)),
                ('custom_interests', models.JSONField(help_text='User-added interests', default=list, blank=True)),
                ('lifestyle', models.JSONField(help_text='List of lifestyle choices', default=list, blank=True)),
                ('music_genres', models.JSONField(help_text='List of music genres', default=list, blank=True)),
                ('dealbreakers', models.JSONField(help_text='List of dealbreakers', default=list, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='residences.residence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(normalize_ranges, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(copy_old_to_new, reverse_code=restore_old_from_new),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(study_level__gte=1, study_level__lte=5),
                name='check_study_level_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(noise_sensitivity__gte=1, noise_sensitivity__lte=5),
                name='check_noise_sensitivity_range',
            ),
        ),
    ]
