# Generated by Django 5.2.13 on 2026-04-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_delete_studentprofile'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('chronotype', models.CharField(blank=True, choices=[('morning', 'Madrugador/a'), ('midday', 'Normal'), ('night', 'Nocturno/a')], max_length=20)),
                ('study_level', models.IntegerField(default=3, help_text='1-5 scale')),
                ('noise_sensitivity', models.IntegerField(default=3, help_text='1-5 scale')),
                ('temperature_preference', models.CharField(blank=True, choices=[('cold', 'Frío'), ('cool', 'Fresco'), ('warm', 'Cálido'), ('hot', 'Muy cálido')], max_length=20)),
                ('order_level', models.CharField(blank=True, choices=[('very_messy', 'Muy desorganizado'), ('somewhat_messy', 'Un poco desordenado'), ('organized', 'Organizado'), ('very_organized', 'Muy organizado')], max_length=20)),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of interest strings')),
                ('custom_interests', models.JSONField(blank=True, default=list, help_text='User-added interests')),
                ('lifestyle', models.JSONField(blank=True, default=list, help_text='List of lifestyle choices')),
                ('music_genres', models.JSONField(blank=True, default=list, help_text='List of music genres')),
                ('dealbreakers', models.JSONField(blank=True, default=list, help_text='List of dealbreakers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='residences.residence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
