from django.urls import path
from .views import (
    ObjectListView,
    ObjectDetailView,
    ObjectLabelListCreateView,
    ObjectLabelDetailView,
    ObjectAvailabilityView,
    ObjectReserveView,
    ObjectCancelView,
    ObjectCompleteRentalView,
    ObjectAdminCancelRentalView,
    ObjectRentalsView,
    UserReservationsView,
    UserObjectNotificationsView,
    UserDismissReservationView,
    AdminAllObjectRentalsView,
    AdminObjectNotificationsView,
    UserPendingRemindersCountView,
    UserMarkRemindersAsViewedView,
)

urlpatterns = [
    path('objects/', ObjectListView.as_view(), name='object-list'),
    path('objects/labels/', ObjectLabelListCreateView.as_view(), name='object-label-list-create'),
    path('objects/labels/<int:label_id>/', ObjectLabelDetailView.as_view(), name='object-label-detail'),
    path('objects/<int:object_id>/', ObjectDetailView.as_view(), name='object-detail'),
    path('objects/<int:object_id>/availability/', ObjectAvailabilityView.as_view(), name='object-availability'),
    path('objects/<int:object_id>/reserve/', ObjectReserveView.as_view(), name='object-reserve'),
    path('objects/<int:object_id>/cancel/', ObjectCancelView.as_view(), name='object-cancel'),
    path('objects/<int:object_id>/rentals/', ObjectRentalsView.as_view(), name='object-rentals'),
    path('objects/<int:object_id>/rentals/<int:rental_id>/complete/', ObjectCompleteRentalView.as_view(), name='object-rental-complete'),
    path('objects/<int:object_id>/rentals/<int:rental_id>/admin-cancel/', ObjectAdminCancelRentalView.as_view(), name='object-admin-rental-cancel'),
    path('my-reservations/reminders/unread-count/', UserPendingRemindersCountView.as_view(), name='user-reminders-unread-count'),
    path('my-reservations/reminders/mark-as-viewed/', UserMarkRemindersAsViewedView.as_view(), name='user-reminders-mark-as-viewed'),
    path('my-reservations/', UserReservationsView.as_view(), name='user-reservations'),
    path('objects/notifications/', UserObjectNotificationsView.as_view(), name='user-object-notifications'),
    path('my-reservations/<int:rental_id>/dismiss/', UserDismissReservationView.as_view(), name='user-reservation-dismiss'),
    path('admin/objects/rentals/', AdminAllObjectRentalsView.as_view(), name='admin-all-object-rentals'),
    path('admin/objects/notifications/', AdminObjectNotificationsView.as_view(), name='admin-object-notifications'),
]