# Generated by Django 5.2.12 on 2026-04-06 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('URGENT', 'Urgente'), ('MAINTENANCE', 'Mantenimiento'), ('EVENT', 'Evento'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Categoría')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('announcement_date', models.DateField(verbose_name='Fecha del aviso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tenants.client', verbose_name='Residencia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-publication_date', '-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['residence', 'category'], name='announcemen_residen_ae1d98_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publication_date'], name='announcemen_publica_2e2e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', 'viewed_at'], name='announcemen_user_id_7abf11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together={('announcement', 'user')},
        ),
    ]
