# Generated by Django 5.2.12 on 2026-04-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=20)),
                ('study_location', models.CharField(blank=True, max_length=100)),
                ('social_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekend_return', models.CharField(blank=True, max_length=50)),
                ('outside_plans_importance', models.CharField(blank=True, max_length=50)),
                ('desired_activity', models.CharField(blank=True, max_length=50)),
                ('order_importance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('noise_tolerance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('smoking_vaping', models.CharField(blank=True, max_length=50)),
                ('visitors_preference', models.CharField(blank=True, max_length=100)),
                ('basic_items_preference', models.CharField(blank=True, max_length=100)),
                ('temperature_preference', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the resident has completed their preference form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(limit_choices_to={'role__name__iexact': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_preferences', to='membership.membership')),
            ],
            options={
                'verbose_name': 'Resident Preference',
                'verbose_name_plural': 'Resident Preferences',
                'ordering': ['-created_at'],
            },
        ),
    ]
