# Generated by Django 5.2.12 on 2026-03-04 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('onboarding', '0003_remove_old_preference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentpreference',
            name='membership',
            field=models.OneToOneField(limit_choices_to={'role__name__iexact': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_preferences', to='membership.membership'),
        ),
    ]
