# Generated by Django 5.2.11 on 2026-03-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0F4C81', max_length=7)),
                ('secondary_color', models.CharField(default='#F4B400', max_length=7)),
                ('accent_color', models.CharField(default='#2E7D32', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='residences.residence')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='residences.residence')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
