# Generated by Django 5.2.11 on 2026-02-19 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('timezone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0F4C81', max_length=7)),
                ('secondary_color', models.CharField(default='#F4B400', max_length=7)),
                ('accent_color', models.CharField(default='#2E7D32', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('residence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='residences.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('portfolio_admin', 'Admin de grupo'), ('residence_admin', 'Admin de residencia'), ('resident', 'Residente')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='residences.residence')),
            ],
            options={
                'ordering': ['user_id', 'role'],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'residence'), name='uniq_membership_user_role_residence')],
            },
        ),
    ]
