# Generated by Django 5.2.13 on 2026-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
        ('residents', '0002_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
