# Generated by Django 5.2.11 on 2026-02-19 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='residences.residence')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
