# Generated by Django 5.2.11 on 2026-03-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_residencedomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
