# Generated by Django 5.2.13 on 2026-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencebranding',
            name='legal_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
