# Generated by Django 5.2.12 on 2026-03-15 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location_type', models.CharField(choices=[('habitacion', 'Mi Habitación'), ('baño', 'Baño Común'), ('cocina', 'Cocina'), ('comedor', 'Comedor'), ('exterior', 'Zonas Exteriores'), ('salas_comunes', 'Salas Comunes')], max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'BAJA'), ('high', 'URGENTE')], default='low', max_length=10)),
                ('assigned_external_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal externo u otro')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidences', to='staff.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Admin', max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidences.incidence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
