# Generated by Django 5.2.12 on 2026-03-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
