# Generated by Django 5.2.12 on 2026-03-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0001_initial'),
        ('incidences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='room_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidences', to='bedrooms.bedroom'),
        ),
    ]
