# Generated by Django 5.2.12 on 2026-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidences', '0002_incidence_is_active_incidence_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='priority',
            field=models.CharField(choices=[('low', 'BAJA'), ('high', 'URGENTE')], default='low', max_length=10),
        ),
    ]
