# Generated by Django 5.2.12 on 2026-04-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('planta', models.IntegerField(blank=True, null=True)),
                ('capacidad_maxima', models.IntegerField(default=1)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble'), ('Triple', 'Triple')], default='Individual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edificio', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedrooms', to='residences.residence')),
            ],
            options={
                'ordering': ['residence_id', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('residence', 'numero', 'edificio'), name='unique_room_per_residence')],
            },
        ),
    ]
