# Generated by Django 5.2.11 on 2026-03-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='edificio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
