# Generated by Django 5.2.11 on 2026-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0002_bedroom_edificio'),
        ('residences', '0002_residencedomain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bedroom',
            constraint=models.UniqueConstraint(fields=('residence', 'numero', 'edificio'), name='unique_room_per_residence'),
        ),
    ]
